# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php
dist: trusty

php:
  - 7.1

matrix:
  fast_finish: true

jdk:
  - oraclejdk8

before_install:
  - php -v
  - 'cd my-project; composer install;'
  - 'vendor/acquia/blt/bin/blt artifact:build'
  - 'ls -al'

install:
  - echo "running install.";

script:
  - echo "running script";
